name: elt_env
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - dbt-core
  - dbt-postgres
  - geopandas
  - pyarrow
  - pytest
  - python=3.11
  - seaborn
  - jupyterlab
  - python-duckdb
  - mypy
  - pandas-stubs
  - pip:
    - dbt-duckdb

